language: java
install:
- sudo chmod +x ../apache-maven-3.2.3/bin/mvn
- ../apache-maven-3.2.3/bin/mvn clean install
before_install:
  # download the latest android sdk and unzip
  - cd com.thanhgiong.note8/
  
