language: java
install:
- ../apache-maven-3.2.3/bin/mvn clean install
before_install:
  # download the latest android sdk and unzip
  - sudo chmod +x apache-maven-3.2.3/bin/*.*
  - cd com.thanhgiong.note8/
  
