language: java
env:
    global:
    - MAVEN_HOME=$PWD/apache-maven-3.2.3-bin
before_install:
  - wget http://archive.apache.org/dist/maven/maven-3/3.2.3/binaries/apache-maven-3.2.3-bin.zip
  - unzip -qq apache-maven-3.2.3-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.2.3
  - export PATH=$M2_HOME/bin:$PATH
  - export PATH=$MAVEN_HOME/bin:$PATH
  - cd com.thanhgiong.note8/
 install:
 mvn clean install
